### ISSUE TITLE
[FR] Add umask settings for right permission on shared volumes

### ISSUE THREAD

**Issue by hitech95** [shawly/docker-crafty-web#1]
Hi,
the defaulty umask is 0022, allowing to configure the umask would allow to use a volume shared by different services.
For example, my minecraft server volume is also shared via SMB and NFS but the files creted from the container can only be edited bu the specified UID.
My permissions are group based. In this was all the users that are in a specific group can edit the servers files. Right now this should be an easy fix: add something like `umask ${UMASK:-0022}` command on your init file. The umask value is a ENV variable (default value 0022).

For reference: https://codeyarns.com/tech/2017-07-21-how-to-set-umask-for-docker-container.html

**Comment by shawly** [comment]
I'll integrate this as soon as I find some time for that! 
The image is still a bit rough around the edges, I also found a bug that if you change the UID and GID that the files in the /crafty_web folder will still be owned by 1000:1000 so I have to fix that anyway.

**Comment by shawly** [comment]
I just added a new release, the build on DockerHub has been triggered, it will take between 60 to 90 minutes to finish building.

**Comment by hitech95** [comment]
Thanks man that is awesome!

**Comment by shawly** [comment]
Took longer than expected but now the image is up to date, just pull and recreate your container. I also updated the README.md :)
