### ISSUE TITLE
Problem with Java11 and Dynmap

### ISSUE THREAD

**Issue by RevLaw** [shawly/docker-crafty-web#3]
Hey,

I was using the default settings (so java11).

The problem is the dynmap was not starting the render of the world. It just hangs on 
> [13:51:39] [Server thread/INFO]: Full render starting on world 'world'...

I've documented it here: [Dynmap Issue 3303](https://github.com/webbukkit/dynmap/issues/3303)

Hope you or java can fix this for the future.

**Comment by shawly** [comment]
This is a Dynmap issue, I cannot fix it nor could it be fixed in Java, the Dynmap devs have to fix this, please contact them.
